### ISSUE TITLE
404 page errors wordplate theme

### ISSUE THREAD

**Issue by sandrodz** [wordplate/wordplate#176]
```
Notice: Trying to get property of non-object in /www/lithuanianbakery.dev/public/themes/wordplate/functions.php on line 68

Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in /www/lithuanianbakery.dev/public/themes/wordplate/functions.php:68 Stack trace: #0 /www/lithuanianbakery.dev/public/themes/wordplate/functions.php(68): trim(NULL) #1 /www/lithuanianbakery.dev/public/wordpress/wp-includes/class-wp-hook.php(300): WordPlate\Application->{closure}(' Page not foun...') #2 /www/lithuanianbakery.dev/public/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(' Page not foun...', Array) #3 /www/lithuanianbakery.dev/public/wordpress/wp-includes/general-template.php(1218): apply_filters('wp_title', ' Page not foun...', '', '') #4 /www/lithuanianbakery.dev/public/themes/wordplate/library/pug-data.php(4): wp_title('', false) #5 /www/lithuanianbakery.dev/public/themes/wordplate/index.php(4): include('/www/lithuanian...') #6 /www/lithuanianbakery.dev/public/wordpress/wp-includes/template-loader.php(74): include('/www/lithuanian...') #7 /www/lithuanianbakery.dev/public/wordpress/wp-blog-header.php(19): re in /www/lithuanianbakery.dev/public/themes/wordplate/functions.php on line 68```

**Comment by vinkla** [comment]
Please add a better description to your issue with the code which fails (`functions.php:68`).

**Comment by sandrodz** [comment]
oops. sorry.
<img width="598" alt="screen shot 2017-05-05 at 11 10 06 am" src="https://cloud.githubusercontent.com/assets/8479569/25736523/6d491a3c-3183-11e7-9009-3b76524c71b8.png">

**Comment by vinkla** [comment]
Its seem the `$post` object doesn't exist on in the 404 page. Could you try to `dd()` the `$post` object in the `404.php` file in your theme?

**Comment by sandrodz** [comment]
I cannot dd inside 404.php as fatal error happens in functions.php file before theme file gets executed.

but yes $post is null
<img width="1172" alt="screen shot 2017-05-05 at 12 42 16 pm" src="https://cloud.githubusercontent.com/assets/8479569/25738847/51e6f3d8-3190-11e7-8a31-8335f1690931.png">

**Comment by vinkla** [comment]
Okay, we'll have to do some debugging on this. If you find a solutions, please let us know!

**Comment by puredazzle** [comment]
@sandrodz are you using any more plugins or something that interfere with the wp_title? I am using the latest version of WordPlate and I don't get this error.

**Comment by sandrodz** [comment]
@puredazzle this is my composer.json
I use cmb2 and polylang, later one does some magic to wp_title, but why does this happen only on 404?

```
{
    "name": "wordplate/wordplate",
    "description": "A modern WordPress stack. Don't repeat yourself.",
    "keywords": ["wordplate", "wordpress", "boilerplate", "plate"],
    "license": "MIT",
    "require": {
        "php": "^7.0",
        "wordplate/framework": "^5.1",
        "wordplate/plate": "^2.3",
        "johnpbloch/wordpress": "4.7.4",
        "wordplate/autoloader": "^0.1.2",
        "pug-php/pug": "^2.5",
        "wpackagist-plugin/cmb2": "^2.2",
        "wpackagist-plugin/polylang": "^2.1"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://wpackagist.org"
        }
    ],
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "extra": {
        "installer-paths": {
            "public/mu-plugins/{$name}": [
                "type:wordpress-muplugin",
                "wordplate/plate",
                "wpackagist-plugin/cmb2",
                "wpackagist-plugin/polylang"
            ],
            "public/plugins/{$name}": ["type:wordpress-plugin"],
            "public/themes/{$name}": ["type:wordpress-theme"]
        },
        "wordpress-install-dir": "public/wordpress"
    }
}
```

**Comment by puredazzle** [comment]
@sandrodz it seems that this is not being used any more by WordPress so we will remove the function all together, please see https://github.com/wordplate/wordplate/pull/177

**Comment by vinkla** [comment]
The `wp_title` is deprecated and we've removed it from WordPlate, please see #177.

**Comment by sandrodz** [comment]
Thank you, works great.
