### ISSUE TITLE
WP-CLI throwing fatal error on use

### ISSUE THREAD

**Issue by gmarchildon** [wordplate/wordplate#193]
Hello, 

I'm trying to make WP-CLI work with Wordplate to automate some stuff, but most command seems to throw a Fatal error :

```Fatal error: Uncaught Error: Class 'WordPlate\Application' not found in phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1070) : eval()'d code:37
Stack trace:
#0 phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1070): eval()
#1 phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1032): WP_CLI\Runner->load_wordpress()
#2 phar://C:/Websites/wordplate/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar://C:/Websites/wordplate/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar://C:/Websites/wordplate/wp/php/wp-cli.php(23): WP_CLI\bootstrap()
#5 phar://C:/Websites/wordplate/wp/php/boot-phar.php(8): include('phar://C:/Websi...')
#6 C:\Websites\wordplate\wp(4): include('phar://C:/Websi...')
#7 {main}
  thrown in phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1070) : eval()'d code on line 37
```

I'm currently running PHP 7.2.1, but had the same error on PHP 7.0.8.
I'm using the latest version of Composer, 1.6.2.
I'm also using the latest version of WP-CLI

I tried multiple time recreating the autoloader and deleting the vendor folder, but no luck.

Any idea? Thank you very much!

**Comment by vinkla** [comment]
I'm running the latest version of PHP, WordPlate and Composer on macOS and it is working fine. What commands are you trying to run?

**Comment by gmarchildon** [comment]
when I try something basic like `wp --info`, it works fine, but when I try something like `wp theme activate myTheme`, I get the error. 

For myself, I'm on Windows 10, but I can use WP-CLI without problem with a basic Wordpress install.

Meanwhile, I tried with PHP 7.1.13, but I still get the same error.

**Comment by gmarchildon** [comment]
Just saw that I forgot to copy the first line of the error. The full error is :

```
Fatal error: Uncaught Error: Class 'WordPlate\Application' not found in phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1070) : eval()'d code:37
Stack trace:
#0 phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1070): eval()
#1 phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1032): WP_CLI\Runner->load_wordpress()
#2 phar://C:/Websites/wordplate/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar://C:/Websites/wordplate/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar://C:/Websites/wordplate/wp/php/wp-cli.php(23): WP_CLI\bootstrap()
#5 phar://C:/Websites/wordplate/wp/php/boot-phar.php(8): include('phar://C:/Websi...')
#6 C:\Websites\wordplate\wp(4): include('phar://C:/Websi...')
#7 {main}
  thrown in phar://C:/Websites/wordplate/wp/php/WP_CLI/Runner.php(1070) : eval()'d code on line 37
```

**Comment by fiskhandlarn** [comment]
I'm getting

```
PHP Fatal error:  Uncaught Error: Call to a member function apply_filters() on array in \public\wordpress\wp-includes\plugin.php:203
Stack trace:
#0 \public\wordpress\wp-includes\load.php(316): apply_filters('enable_wp_debug...', true)
#1 \public\wordpress\wp-settings.php(69): wp_debug_mode()
#2 D:\dokument\git\wp-cli\php\WP_CLI\Runner.php(960): require('D:\\dokument\\pro...')
#3 D:\dokument\git\wp-cli\php\WP_CLI\Runner.php(904): WP_CLI\Runner->load_wordpress()
#4 D:\dokument\git\wp-cli\php\wp-cli.php(21): WP_CLI\Runner->start()
#5 D:\dokument\git\wp-cli\php\boot-fs.php(17): include('D:\\dokument\\git...')
#6 {main}
  thrown in \public\wordpress\wp-includes\plugin.php on line 203
```

when trying `wp` or `wp --help`. `wp --info` seems to work as expected though.

**Comment by vinkla** [comment]
@fiskhandlarn thanks for reporting! 

This is most likely an issue on Windows. I wont be able to debug this since I'm running macOS. If anyone finds a solutions, please share it in this issue. We want this to work across all platforms.

**Comment by vinkla** [comment]
@gmarchildon yeah, maybe this could be related to this:

> Modifying wp-config.php beyond constant definitions is not best practice. You should move any modifications to a WordPress mu-plugin, which will retain the functionality of your modifications while allowing wp-cli to parse your wp-config.php without throwing a PHP error, as well as preventing other errors.

**Comment by aaemnnosttv** [comment]
@fiskhandlarn can you share the output of your `wp --info`?

It sounds like this could be the same issue described in wp-cli/wp-cli#3388 which indicates WP-CLI may be installed improperly. Perhaps try reinstalling/upgrading WP-CLI and see if the issue persists for you.

**Comment by fiskhandlarn** [comment]
@aaemnnosttv

**Comment by fiskhandlarn** [comment]
@aaemnnosttv 

```
$ wp --info
PHP binary:     C:\Program Files\php-7.1.9-Win32-VC14-x64\php.exe
PHP version:    7.1.9
php.ini used:   C:\Program Files\php-7.1.9-Win32-VC14-x64\php.ini
WP-CLI root dir:        D:\dokument\git\wp-cli
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  <obfuscated>\wp-cli.yml
WP-CLI version: 0.25.0-alpha
```

**Comment by aaemnnosttv** [comment]
Looks like you're using an older version of WP-CLI which you might have installed via git?

Try updating WP-CLI and see if that solves it for you.

**Comment by fiskhandlarn** [comment]
@aaemnnosttv I agree, it looks like that. I've installed `wp-cli` via `composer global`, and the version there is 1.4.1.

**Comment by fiskhandlarn** [comment]
@aaemnnosttv No wait, I had a bash alias to an older version, sorry!

**Comment by fiskhandlarn** [comment]
`wp-cli` seems to work for me now! At least `wp`, `wp --help`, `wp theme activate theme`.

**Comment by fiskhandlarn** [comment]
@aaemnnosttv I'm noticing you're trying to run `wp theme activate myTheme`. Could it be a case issue on Windows? Have you tried activating a theme with only lowercase in it's name?

**Comment by gmarchildon** [comment]
I figured you were talking to me from the command. The command `wp theme activate myTheme` was just an exemple, actually, I only write `wp theme activate` to prompt the explinations (that works on my classic Wordpress install) so it's not relatate to the name of my theme since I don't even put one. From my guess, the path to the vendor that is given to WP-CLI is not the right one.

**Comment by fiskhandlarn** [comment]
@gmarchildon Yeah, sorry, I meant you of course. :)

So:

1. What exact `wp-cli` command are you trying to run when you get the error message in https://github.com/wordplate/wordplate/issues/193#issue-289727563?
2. What version of `wp-cli` are you using and how have you installed it?
3. What's the output when you run `wp --info`?

**Comment by gmarchildon** [comment]
@fiskhandlarn 

1. `wp theme activate`

2. The latest (so 1.4.1), freshly download from `curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar`

3. 
```PHP binary:     C:\OylexWamp\php-7.2.1-nts\php.exe
PHP version:    7.2.1
php.ini used:   C:\OylexWamp\php-7.2.1-nts\php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       C:\websites\wordplate
WP-CLI packages dir:    C:\Users\Marchildon/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:  C:\websites\wordplate\wp-cli.yml
WP-CLI version: 1.4.1```

**Comment by aaemnnosttv** [comment]
@gmarchildon can you share the error output you're seeing now that you're using the latest WP-CLI? Also, what version of WordPlate are you using?

**Comment by gmarchildon** [comment]
@aaemnnosttv I'm using the latest version of WP-CLI since the start, I acutally redownloaded it multiple time (it's part of my install script). For Wordplate, same, latest version from `composer create-project wordplate/wordplate`. I saw the update yesterday, but changed nothing, same exact error as my first post.

**Comment by vinkla** [comment]
@gmarchildon @aaemnnosttv @fiskhandlarn did you find a solution?

**Comment by fiskhandlarn** [comment]
@vinkla No, I'm unable to reproduce this issue.

@gmarchildon Have you tried installing `wp-cli` version 1.4.1 via `composer global`? (That's basically the only difference I can think of, besides different PHP versions.)

**Comment by vinkla** [comment]
I'm closing this due to inactivity. Please write if this is still an issue.
